Criando object UserInputReader
devpass-tech/challenge-foundations-kotlin pull request #37
Opened 2023-01-22 16:42 UTC by KauaRasera

Esse `object` deve ter dois métodos:

1. `readRawSalary() : Double`, essa função deve utilizar o método de leitura de input no terminal para pedir o salário bruto do usuário do sistema.
2. `readUserName() : String`, essa função deve utilizar o método de leitura de input no terminal para pedir o nome do usuário do sistema

**Importante:** você deve fazer a validação dos valores inputados nos dois métodos, e, em caso de invalidade, levantar exceções específicas que herdam `OwnedException`, para termos controle das exceções que estamos levantando.

**Validações:**

- Nome em branco.
- Nome com números.
- Salário negativo.
- Salário com valores não numéricos.

### Critérios de aceitação

- [ ]  A classe implementa adequadamente os dois métodos indicados.
- [ ]  Os métodos validam as informações inputadas de maneira condizente e levantam exceções que herdam `OwnedException` nos casos necessários.

2023-01-23 13:23 UTC, michel05 commented on solutions/devsprint-michel-ferreira-2/src/main/kotlin/salarioLiquido/UserInputReader.kt
> +        val salary = reader.nextDouble()
Boa, bora tentar garantir essas quatro validações: 
Nome em branco. InvalidInputFormatNameException
Nome com números. InvalidInputFormatNameException
Salário negativo. InvalidRawSalaryException [OK] 
Salário com valores não numéricos InvalidInputFormatSalaryException

Uma dica é ao invés de usar nextDouble() usar sempre readLine() que lê como String, e então tentarmos converter para Double, aplicando as validações.

Para ficar mais clean, você pode criar um método apenas para validar cada input, por exemplo:

```
fun readUserName(): String {
        print("Enter username: ")
        val userName = readLine()

        validateUserName(userName)
        return userName
}

private fun validateUserName(userName: String?) {
  if(userName == null) throws InvalidInputFormatNameException("")
  // Outras validações
}
```

2023-01-23 13:56 UTC, michel05 requested changes

2023-01-23 13:56 UTC, michel05 commented on solutions/devsprint-michel-ferreira-2/src/main/kotlin/salarioLiquido/UserInputReader.kt
> +
Boa, bora tentar garantir essas quatro validações: 
Nome em branco. **InvalidInputFormatNameException**
Nome com números. **InvalidInputFormatNameException**
Salário negativo. **InvalidRawSalaryException** [**OK**] 
Salário com valores não numéricos **InvalidInputFormatSalaryException**

**Dica**: ao invés de usar nextDouble() usar sempre readLine() que lê como String, e então tentarmos converter para Double, aplicando as validações.

Para ficar mais clean, você pode criar um método apenas para validar cada input, por exemplo:

```
fun readUserName(): String {
        print("Enter username: ")
        val userName = readLine()

        validateUserName(userName)
        return userName
}

private fun validateUserName(userName: String?) {
  if(userName == null) throws InvalidInputFormatNameException("")
  // Outras validações
}
```

2023-01-24 13:28 UTC, michel05 requested changes

2023-01-24 13:28 UTC, michel05 commented on solutions/devsprint-michel-ferreira-2/src/main/kotlin/salarioLiquido/UserInputReader.kt
> +    fun readRawSalary() {
Top show de bola, só mais um ponto:

Essa função deve retornar o Salário informado, então a assinatura dela deve ser semelhante ao da leitura do nome:
```
fun readRawSalary() : Double {
  val readerSalary = readLine()
  val salaryValidated = validateSalary(readerSalary )
  return salaryValidated 
}
```

E a função de validação teria cada validação de forma unitária, por exemplo:

```
private fun validateSalary(readerSalary: String?): Double {
    if (readerSalary == null)
        throw InvalidRawSalaryException("Invalid data, please enter a valid value")
    val salaryAsDouble = try {
        readerSalary.toDouble()
    } catch (ex: NumberFormatException) {
        throw InvalidInputFormatSalaryException("Salary with non-numeric values, please enter a valid value")
    }
    if(salaryAsDouble <= 0.0)  throw InvalidInputFormatSalaryException("Negative salary, please enter a valid value")
    
    return salaryAsDouble
}
```

2023-01-24 14:12 UTC, KauaRasera commented on solutions/devsprint-michel-ferreira-2/src/main/kotlin/salarioLiquido/UserInputReader.kt
> +    fun readRawSalary() {
Beleza, eu estava com essa duvida mesmo. Vou ajeitar

2023-01-24 14:35 UTC, michel05 requested changes

2023-01-24 14:35 UTC, michel05 commented on solutions/devsprint-michel-ferreira-2/src/main/kotlin/salarioLiquido/UserInputReader.kt
> +        throw InvalidInputFormatNameException("Name with numbers, please enter a valid username")
Nesse último throw voce precisa colocar uma condição para poder validar ele, caso contrário ele vai lançar sempre.
O primeiro throw que valida se o userName está nulo, está correto.

Por exemplo:

```
if ( a + b == c) {
        throw InvalidInputFormatNameException("Name with numbers, please enter a valid username")
}
```

Ou seja, só deve lançar a exceção se a + b == c 
;)

2023-01-24 14:35 UTC, michel05 commented on solutions/devsprint-michel-ferreira-2/src/main/kotlin/salarioLiquido/UserInputReader.kt
> +        print("Inform gross salary: ")
Aqui ficou top, só o print que ficou depois do readLine()

2023-01-24 21:33 UTC, merged