Feature/resource reader
devpass-tech/challenge-foundations-kotlin pull request #4
Opened 2022-08-02 20:21 UTC by Pedroajs

### O que é

Criar um `object` chamado `ResourceReader`, que implemente a interface `IResourceReader`, e consiga fazer a leitura de arquivos de dentro da pasta `resources`.

A sua implementação deve, ao final da execução, retornar uma lista de todas as linhas de um dado arquivo dentro da pasta `resources`.

Minha maior dúvida quanto a essa tarefa foi como acessar a pasta resources e ler o arquivo txt. Para isso usei o File IO, mas a dúvida persiste. Não sei se está exatamente correto.

### Critério de aceitação

- [ ]  A implementação funciona adequadamente
- [ ]  O `object` foi criado no `package` adequado

2022-08-02 20:42 UTC, victorsilva95 commented
Oi Pedro, cara vê se esse link pode te ajudar com tua duvida:
https://github.com/Incognitowski/kotlin-class-by-class/blob/master/src/main/kotlin/kt17readingFromResources/Main.kt
qualquer coisa se ainda a duvida persistir pode entrar em contato comigo sem problema.

2022-08-02 20:50 UTC, victorsilva95 requested changes

2022-08-02 20:50 UTC, victorsilva95 commented on solutions/devsprint-luiz-zytkowski-1/src/main/kotlin/framework/ResourceReader.kt
> +        } catch (error: FileNotFoundException){
Cara parabéns pela preocupação de tratar e exceção que pode ocorrer na hora de realizar a leitura do arquivo, mas a gente criou uma task no futuro para realizar esse tratamento utilizando inclusive a classe Loggable, por enquanto se preocupa somente em realizar a leitura.

2022-08-02 21:12 UTC, Pedroajs commented on solutions/devsprint-luiz-zytkowski-1/src/main/kotlin/framework/ResourceReader.kt
> +        } catch (error: FileNotFoundException){
Opa, valeu! Dei uma mexida aqui, mas travei. Tirei esse tratamento de erro, tudo certo. Mas agora tem um erro de NullPointerException quando chamo o método na main pra testar.

2022-08-02 21:13 UTC, Incognitowski requested changes
Pedro, sua solução é inteligente em tentar ler o arquivo utilizando ```File()```, porém, nessa tarefa, queremos ler especificamente um arquivo de dentro da pasta ```resources```. 

Volto a mencionar o link que o @victorsilva95 indicou para consulta: https://github.com/Incognitowski/kotlin-class-by-class/blob/master/src/main/kotlin/kt17readingFromResources/Main.kt

Esse código lê especificamente arquivos de dentro de ```resources```, que é o que precisamos para essa solução 😉 

Ah, e queria reforçar os parabéns dados pelo @victorsilva95 sobre a preocupação com o tratamento de erro! Boa!

2022-08-02 21:37 UTC, Pedroajs commented
>  Obrigado, luiz! Fiz umas alterações. Agora o erro é outro. Vou vendo como resolver.

2022-08-03 14:47 UTC, Incognitowski submitted a review, later dismissed
Boa! Mandou bem, mano! 🚀

2022-08-03 16:10 UTC, victorsilva95 approved these changes

2022-08-03 21:33 UTC, Incognitowski commented
Pedro, dá uma olhada na linha 49 desse arquivo aqui: https://github.com/Incognitowski/kotlin-class-by-class/blob/master/src/main/kotlin/kt04strings/Main.kt

Acho que pode deixar sua solução mais limpa 😉

2022-08-04 14:46 UTC, Incognitowski commented
Pedro, tem alterações em arquivos que não deveriam ser alterados, e também a exclusão dos arquivos que a galera inseriu ontem! Se puder reverter essas alterações, dai revisamos o código novamente 😁

2022-08-04 16:26 UTC, victorsilva95 requested changes

2022-08-04 16:26 UTC, victorsilva95 commented on solutions/devsprint-luiz-zytkowski-1/src/main/kotlin/framework/ResourceReader.kt
> +    class DoesNotStartsWith(message: String) : OwnedException(message)
Não seria melhor, colocarmos essa classe de exception em um package especifico de exception e usa-la aqui?

2022-08-04 17:41 UTC, closed without merging