KT1-6 Created Data Class NetAmountResult
devpass-tech/challenge-foundations-kotlin pull request #5
Opened 2022-08-02 21:45 UTC by RiellyCM

Esse `data class` representará a resposta da nossa função de cálculo de salário líquido. A ideia é retornar um conjunto de informações interessantes para não mostrarmos simplesmente o valor final para o usuário, mas sim um resumo de diversas informações “coletadas” durante o cálculo.

### Critérios de aceitação

- [X]  A `data class` foi criada no `package` adequado

- [X] A `data class` possui propriedades que são condizentes com sua finalidade.

2022-08-02 21:50 UTC, Incognitowski commented on solutions/devsprint-luiz-zytkowski-1/src/main/kotlin/Main.kt
> +import salarioLiquido.NetAmountValues
Esse import aqui pode ser removido, visto que não está sendo usado no código da main (ainda). Mas isso já me indica que testou seu código de alguma maneira, então parabéns por isso! 😉

2022-08-02 21:53 UTC, Incognitowski requested changes

2022-08-02 21:53 UTC, Incognitowski commented on solutions/devsprint-luiz-zytkowski-1/src/main/kotlin/salarioLiquido/NetAmountValues.kt
> +data class NetAmountResult (
Adorei o nome! ```NetAmountResult``` ficou show 🚀

2022-08-02 21:53 UTC, Incognitowski commented on solutions/devsprint-luiz-zytkowski-1/src/main/kotlin/salarioLiquido/NetAmountValues.kt
> +    override fun toString(): String {
Essa implementação ficou show! Mas por hora vamos nos preocupar só com a criação da data class. Lá na [KT1-12] nós vamos implementar algo assim, só que utilizando extension functions.

2022-08-03 14:49 UTC, Incognitowski approved these changes
Nice! Task concluída ao meu ver 😉

2022-08-03 15:10 UTC, Incognitowski approved these changes

2022-08-03 16:06 UTC, victorsilva95 approved these changes

2022-08-03 21:35 UTC, merged